#application.yml#spring.data.mongodb.url=mongodb+srv://anujSpringBoot:Anuj2005@cluster0.pll7bh0.mongodb.net/?appName=Cluster0
#spring.application.name=journalApp
#spring.data.mongodb.auto-index-creation=true

spring:
  application:
    name: journalApp


  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      uri: mongodb+srv://anujSpringBoot:Anuj2005@cluster0.pll7bh0.mongodb.net/?appName=Cluster0
      auto-index-creation: true


  mail:
    host : smtp.gmail.com
    port : 587
    username : anujgosavi2005@gmail.com
    password : kaky dfop geat zfea
    properties:
       mail :
          smtp :
            auth : true
            starttls :
              enable : true




server:
  port: 8080



weather.api.key: 7250b84fae215ef026c25d7e7cd5bd5a